apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-scripts
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
data:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "scripts/*.py" }}
  {{ $path | base }}: |
{{ $files.Get $path | indent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-environment
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
data:
  DELIMITER: "|"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-last-seen-{{ .Values.postType }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
data:
  LAST_SEEN_DATE: "1969-12-31T19:00:00.000Z"
  LAST_SEEN_POSTS: "N/A"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name}}-webhooks-{{ .Values.postType }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app: {{ template "name" . }}
type: Opaque
data:
  SLACK_BEST_NEW_MUSIC_WEBHOOK: {{ .Values.webhookUrl | b64enc }}